name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: trade.truehealthayurveda.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Ai-Bot-Trader
            git reset --hard HEAD
            git pull origin main
            # Ensure permissions are correct after pull
            sudo chown -R ubuntu:www-data .
            sudo chmod -R 775 .
            # Restart the service
            sudo systemctl restart trading_bot
